name: 'test-action-summary'
description: 'Test summary wf'

on:
  workflow_dispatch:

jobs:
  run-test:
    runs-on: ubuntu-20.04
    steps:
      - name: run-test
        run: |
          echo "Running..."
      - uses: onshape/onshape-action-summary@main
